# This file was generated by chatGPT
FROM golang:1.24.3-alpine AS builder

WORKDIR /app

# Add go mod files and download deps
COPY go.mod go.sum ./
RUN go mod download

# Copy source
COPY . .

# Copy assets specifically. src dest. Paths relative to Workdir above
COPY assets/ ./assets/

# Build binary
RUN go build -o auth-api ./cmd/main.go

# Final stage
FROM alpine:latest

WORKDIR /root/
COPY --from=builder /app/auth-api .

EXPOSE 8976

ENTRYPOINT ["./auth-api"]

